/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package TaskTracker;

import java.io.IOException;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

@WebServlet("/hello")
public class Library extends HttpServlet
{
    /**
     *
     */
    private static final long serialVersionUID = 1L;

    public boolean someLibraryMethod() {
        return true;
    }

    @Override
    protected void doGet(HttpServletRequest req, HttpServletResponse resp) throws ServletException, IOException
    {
        resp.getWriter().println("Hello there!");
    }
}
