/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package TaskTracker;

import org.junit.jupiter.api.Test;
//import static org.junit.jupiter.api.Assertions.*;

class LoginTest {
    @Test void testSomeLibraryMethod() {
        //LoginServlet classUnderTest = new LoginServlet();
        //assertTrue(classUnderTest, "someLibraryMethod should return 'true'");
    }
}
